/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * recibe.java
 *
 *
 * Created on 11/04/2011, 12:16:02 PM
 */
import java.io.*;
import java.util.*;

/**
 *
 * @author Esteban
 */
public class recibe extends javax.swing.JFrame {
private ArrayList listeners;
     WriterPort  emisor;
     ReaderPort  reader;
     String a =""; String dato;

    /** Creates new form recibe */
    public recibe() {
        initComponents();
     this.emisor= WriterPort.getInstance();

        this.reader = ReaderPort.getInstance();
        this.reader.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ActionEventPort actionEventPort = (ActionEventPort)evt;
                portReadData(actionEventPort);
            }
        }
        );



    }

      public void portReadData(ActionEventPort actionEventPort){

        a+=actionEventPort.getReaded();
        //area1.setText(area1.getText() + a  + "\n");
        int flagi=0; int flagf=0;
        int l= a.length();
        for (int i=0; i<l;i++){
            char q = a.charAt(i);
            if (q=='@'){
                flagi=1;
            }if (q=='#'){
                flagf=1;
              
            }if ((flagi==1)&&(flagf==1)) {
                dato = a.substring(1,l-1);
              
            }

        }
area1.setText(dato);
    }





    
    


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        area1 = new javax.swing.JTextField();
        b1 = new javax.swing.JRadioButton();
        b2 = new javax.swing.JRadioButton();
        ack = new javax.swing.JButton();
        borrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("receptor");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 20, 80, 14);

        area1.setText("esperando mensaje...");
        getContentPane().add(area1);
        area1.setBounds(70, 40, 250, 100);

        b1.setText("MANUAL");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(70, 140, 120, 23);

        b2.setText("AUTOMATICO");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(70, 170, 150, 23);

        ack.setText("CONFIRMAR");
        ack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ackActionPerformed(evt);
            }
        });
        getContentPane().add(ack);
        ack.setBounds(60, 230, 110, 23);

        borrar.setText("BORRAR");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        getContentPane().add(borrar);
        borrar.setBounds(190, 230, 130, 23);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-416)/2, (screenSize.height-338)/2, 416, 338);
    }// </editor-fold>//GEN-END:initComponents

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed

         a="";
        area1.setText("");

    }//GEN-LAST:event_borrarActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed

        if((b2.isSelected()) ){
       b1.setSelected(false);
       
       ack.setEnabled(false);

       
        try {
        String datos;

        datos = "@OK#";
        char a = (char)(13);
        this.emisor.escribir(datos + a);


        }
        catch(IOException iOException){

        }
     
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void ackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ackActionPerformed

       try {
        String datos;

        datos = "@OK#";
        char a = (char)(13);
        this.emisor.escribir(datos + a);


        }
        catch(IOException iOException){

        }
    }//GEN-LAST:event_ackActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
if(b1.isSelected()){
       b2.setSelected(false);
      ack.setEnabled(true);

        } 
    }//GEN-LAST:event_b1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recibe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ack;
    private javax.swing.JTextField area1;
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton b2;
    private javax.swing.JButton borrar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
